name: build-release-deploy
on:
  push:
    branches:
      - staging

jobs:
  build-release:
    uses: mailprotector/workflows/.github/workflows/build-ecr-single.yml@main
    with:
      ECR_REPOSITORY: dns-healthcheck 
    secrets:
      AWS_IAM_ROLE_ARN: ${{ secrets.STAGING_IAM_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
